# Generated by Django 4.1 on 2022-08-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='upload_file',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
