# Generated by Django 4.1 on 2022-08-31 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_article_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='upload_file',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/'),
        ),
    ]
